import type { CarbonController, Device, SyncJob, TimelineSession } from './types';

export const overviewBullets = [
  'Connect IQ devient le chemin nominal entre la fenix 7 Pro, l Edge 1030 et le companion mobile.',
  'Le Carbon TLS est pilote par nouvelleApp avec des controles vitesse et incline dans le mobile.',
  'iFIT devient optionnel et reste limite a un usage legacy d import si necessaire.',
  'Les diagnostics mettent en avant les bridges materiels incomplets avant la timeline.',
];

export const initialDevices: Device[] = [
  {
    id: 'phone',
    name: 'Redmi Note 10 Pro',
    role: 'Bridge mobile',
    transport: 'Local host',
    status: 'connected',
    integration: 'Mobile direct',
    lastSeen: 'Maintenant',
    note: 'Le telephone porte la session, les synchros et le pilotage local du tapis.',
    metrics: ['Bridge BLE', 'Session locale', 'Diagnostics'],
    dataPoints: [
      {
        id: 'mobile-session',
        label: 'Session locale',
        value: 'Compte local et pile de synchro actifs',
        state: 'received',
        note: 'Le mobile doit conserver le contexte utilisateur, la session et les jobs en cours.',
      },
      {
        id: 'ble-bridge',
        label: 'Bridge BLE',
        value: 'Scan local et handoff appareil prets',
        state: 'received',
        note: 'Le telephone agrege les bridges de proximite avant de pousser les commandes.',
      },
      {
        id: 'local-diagnostics',
        label: 'Diagnostics locaux',
        value: 'Journal et erreurs de bridge exposes',
        state: 'received',
        note: 'Le mobile doit remonter les ecarts de connexion et les relances de synchro.',
      },
      {
        id: 'carbon-master',
        label: 'Main sur Carbon TLS',
        value: 'Le pont local doit encore prendre la main',
        state: 'pending',
        note: 'nouvelleApp doit devenir le maitre materiel du tapis, sans iFIT intermediaire.',
      },
    ],
  },
  {
    id: 'fenix-7-pro',
    name: 'fenix 7 Pro',
    role: 'Wearable principal',
    transport: 'Connect IQ bridge',
    status: 'connected',
    integration: 'Connect IQ companion',
    lastSeen: '10:42',
    note: 'Montre principale deja reliee. Les lots Connect IQ remontent les metriques P0 et les snapshots journaliers.',
    metrics: ['Heart rate', 'Recovery', 'Daily sync'],
    dataPoints: [
      {
        id: 'heart-rate',
        label: 'Frequence cardiaque live',
        value: 'Flux cardio et zones d effort',
        state: 'received',
        note: 'Donnee prioritaire pour enrichir les seances Carbon TLS et la timeline.',
      },
      {
        id: 'recovery',
        label: 'Recovery / readiness',
        value: 'Charge recente et recuperation',
        state: 'received',
        note: 'Le mobile doit recuperer les indicateurs de fatigue et de reprise.',
      },
      {
        id: 'daily-sync',
        label: 'Sommeil / HRV / sync',
        value: 'Historique bien-etre quotidien',
        state: 'received',
        note: 'Permet de reconciler les seances et le contexte physiologique dans le tableau de bord.',
      },
      {
        id: 'device-health',
        label: 'Etat de la montre',
        value: 'Batterie, dernier contact et stabilite du lien',
        state: 'received',
        note: 'Le companion Connect IQ doit exposer la sante du wearable, la version app et la fraicheur des batches.',
      },
    ],
  },
  {
    id: 'edge-1030',
    name: 'Edge 1030',
    role: 'Compteur principal',
    transport: 'Connect IQ bridge',
    status: 'attention',
    integration: 'Connect IQ direct',
    lastSeen: '09:58',
    note: 'Le compteur est detecte, mais la liaison mobile doit encore etre finalisee.',
    metrics: ['Bike sessions', 'Trainer bridge', 'Zumo path'],
    dataPoints: [
      {
        id: 'bike-activity',
        label: 'Activites velo',
        value: 'Resume FIT et derniere sortie a importer',
        state: 'pending',
        note: 'Le mobile doit recuperer les seances du compteur et leur resume exploitable.',
      },
      {
        id: 'trainer-bridge',
        label: 'Bridge home trainer',
        value: 'Puissance, cadence et resistance non finalisees',
        state: 'blocked',
        note: 'Le canal Connect IQ doit encore finaliser la remontree des donnees trainer.',
      },
      {
        id: 'route-path',
        label: 'Parcours / traces',
        value: 'Traces et parcours detectes, pas encore hydrates',
        state: 'pending',
        note: 'Les itineraies et traces doivent etre visibles dans la timeline velo.',
      },
      {
        id: 'sensor-map',
        label: 'Carte des capteurs',
        value: 'Capteurs velo connus, lien mobile incomplet',
        state: 'pending',
        note: 'Le mobile doit lister les capteurs lies au compteur et leur etat de disponibilite.',
      },
    ],
  },
  {
    id: 'carbon-tls',
    name: 'Carbon TLS',
    role: 'Tapis principal',
    transport: 'Direct local control',
    status: 'ready',
    integration: 'nouvelleApp direct',
    lastSeen: '09:51',
    note: 'Le tapis est decouvert. Le pilotage direct peut etre active depuis le mobile.',
    metrics: ['Speed', 'Incline', 'Workout state'],
    dataPoints: [
      {
        id: 'treadmill-speed',
        label: 'Vitesse live',
        value: 'En attente du bridge direct',
        state: 'pending',
        note: 'nouvelleApp doit lire et piloter la vitesse en temps reel.',
      },
      {
        id: 'treadmill-incline',
        label: 'Incline live',
        value: 'En attente du bridge direct',
        state: 'pending',
        note: 'Le mobile doit afficher et ajuster l incline sans passer par un maitre externe.',
      },
      {
        id: 'workout-state',
        label: 'Etat de seance',
        value: 'Bridge detecte, mais commande inactive',
        state: 'pending',
        note: 'Le mobile doit connaitre le statut exact de la seance et de la minuterie locale.',
      },
      {
        id: 'safety-state',
        label: 'Etat machine / securite',
        value: 'Presence du tapis detectee',
        state: 'pending',
        note: 'Arret urgence, disponibilite machine et etat global doivent etre visibles dans l app.',
      },
    ],
  },
];

export const initialSessions: TimelineSession[] = [
  {
    id: 'session-bike-1',
    title: 'Bloc home trainer Edge + Zumo',
    sport: 'Indoor cycling',
    time: 'Hier 18:40',
    duration: '52 min',
    primaryDevice: 'Edge 1030',
    summary: 'Seance velo reconciliee. Le Edge reste la source principale, le mobile garde la trace du bridge.',
    sources: ['Edge 1030', 'Elite Zumo', 'nouvelleApp'],
  },
  {
    id: 'session-run-1',
    title: 'Seuil Carbon TLS',
    sport: 'Treadmill',
    time: 'Aujourd hui 07:05',
    duration: '36 min',
    primaryDevice: 'Carbon TLS',
    summary: 'Pilotage local du tapis par le mobile. FC associee a la fenix 7 Pro.',
    sources: ['Carbon TLS', 'nouvelleApp', 'fenix 7 Pro'],
  },
  {
    id: 'session-run-2',
    title: 'Footing de recuperation',
    sport: 'Run',
    time: 'Lun 19:15',
    duration: '28 min',
    primaryDevice: 'fenix 7 Pro',
    summary: 'Session simple Connect IQ, sans conflit de sources.',
    sources: ['fenix 7 Pro', 'nouvelleApp'],
  },
];

export const initialSyncJobs: SyncJob[] = [
  {
    id: 'job-1',
    title: 'Sync fenix 7 Pro Connect IQ',
    status: 'success',
    finishedAt: '10:42',
    detail: 'Le wearable principal a publie un batch Connect IQ sans erreur.',
  },
  {
    id: 'job-2',
    title: 'Bridge Carbon TLS',
    status: 'pending',
    finishedAt: '10:14',
    detail: 'Le tapis est visible, mais le pilotage direct n est pas encore active.',
  },
  {
    id: 'job-3',
    title: 'Bridge Edge 1030',
    status: 'partial',
    finishedAt: '09:58',
    detail: 'Le compteur est detecte, mais le canal mobile reste incomplet.',
  },
];

export const initialController: CarbonController = {
  connected: false,
  workoutActive: false,
  speedKph: 9.0,
  inclinePct: 1.5,
  targetMinutes: 24,
};
