export {
  createGarminConnectIqBatchAck,
  GARMIN_CONNECT_IQ_DEVICE_KINDS,
  GARMIN_CONNECT_IQ_LINK_HEALTHS,
  GARMIN_CONNECT_IQ_METRIC_DEFINITIONS,
  GARMIN_CONNECT_IQ_METRIC_KEYS,
  GARMIN_CONNECT_IQ_P0_LIVE_METRICS,
  GARMIN_CONNECT_IQ_P0_SNAPSHOT_METRICS,
  GARMIN_CONNECT_IQ_P1_CONDITIONAL_METRICS,
  GARMIN_CONNECT_IQ_PROTOCOL_VERSION,
  GARMIN_CONNECT_IQ_SAMPLE_QUALITIES,
  GARMIN_CONNECT_IQ_SNAPSHOT_TYPES,
  GARMIN_CONNECT_IQ_SOURCE_DOMAINS,
  GARMIN_CONNECT_IQ_SYNC_DIAGNOSTIC_CODES,
  isGarminConnectIqBatchAck,
  isGarminConnectIqBatchEnvelope,
  isGarminConnectIqDeviceCapabilities,
  isGarminConnectIqMetricKey,
  isGarminConnectIqMetricSample,
  isGarminConnectIqSampleQuality,
  isGarminConnectIqSnapshot,
  isGarminConnectIqSourceDomain,
  isGarminConnectIqSyncDiagnostic,
} from "@nouvelle-app/shared";
