export type {
  GarminConnectIqBatchAck,
  GarminConnectIqBatchEnvelope,
  GarminConnectIqBatchItem,
  GarminConnectIqDeviceCapabilities,
  GarminConnectIqDeviceHello,
  GarminConnectIqDeviceKind,
  GarminConnectIqLinkHealth,
  GarminConnectIqLinkStatus,
  GarminConnectIqMessage,
  GarminConnectIqMetricDefinition,
  GarminConnectIqMetricKey,
  GarminConnectIqMetricSample,
  GarminConnectIqMetricTier,
  GarminConnectIqMetricValue,
  GarminConnectIqSampleQuality,
  GarminConnectIqSnapshot,
  GarminConnectIqSnapshotType,
  GarminConnectIqSourceDomain,
  GarminConnectIqSyncDiagnostic,
  GarminConnectIqSyncDiagnosticCode,
  GarminConnectIqWatchError,
  GarminConnectIqWatchErrorCode,
} from "@nouvelle-app/shared";
